services:

    Markocupic\SacCabinsBundle\Controller\ContentElement\SacCabinsDetailController:
        arguments:
            - '@contao.framework'
            - '@contao.image.studio'
            - '@contao.insert_tag.parser'
            - '@twig'
            - '%markocupic_sac_cabins.geo_link%'
        public: true

    Markocupic\SacCabinsBundle\Controller\ContentElement\SacCabinsListController:
        arguments:
            - '@contao.framework'
            - '@contao.image.studio'
            - '@twig'
        public: true


